---
title: "Bird collisions"
author: "Sara Altman, Bill Behrman"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Packages
library(tidyverse)

# Parameters
file_data <- here::here("data/collisions.rds")

#===============================================================================

# Read in data
collisions <- read_rds(file_data)
```

## Summaries

```{r}
collisions |>
  summary()
```

```{r}
collisions |>
  summarize_all(\(x) sum(is.na(x)))
```

There are no `NA`s.

## 1D EDA

```{r}
collisions |>
  ggplot(aes(date)) +
  geom_histogram(binwidth = 365)
```

It looks like the number of collisions is increasing.

```{r}
collisions |>
  count(genus, species, sort = TRUE)
```

```{r}
collisions |>
  count(genus, sort = TRUE)
```


```{r}
collisions |>
  count(locality, sort = TRUE)
```

There are two localities---McCormick Place and the general Chicago area.

## 2D EDA

```{r}
collisions |>
  ggplot(aes(date)) +
  geom_histogram(binwidth = 365) +
  facet_grid(rows = vars(locality))
```

Chicago collisions are increasing, but McCormick Place collisions actually look like they are going down. 


