---
title: "McCormick Place light scores"
author: "Sara Altman"
date: "2019-05-03"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Library
library(tidyverse)

# Parameters
file_data <- here::here("data/light_mp.rds")

#===============================================================================

light_mp <- read_rds(file_data)
```

# Summary

```{r}
light_mp %>% 
  summary()
```

The light score is the "proportion of the 17 window bays that were illuminated" [1]. The recordings all happened before dawn. 

```{r}
light_mp %>% 
  count(light_score, sort = TRUE)
```

```{r}
light_mp %>% 
  count(date, sort = TRUE)
```

# 1D EDA

```{r}
light_mp %>% 
  ggplot(aes(light_score)) +
  geom_histogram(binwidth = 1)
```

Light tends to be either very low or very high.

```{r}
light_mp %>% 
  ggplot(aes(date)) +
  geom_histogram(binwidth = 250)
```

Data was collected pretty evenly across time.

# 2D EDA

```{r}
light_mp %>% 
  group_by(date) %>% 
  summarize(light_score = median(light_score, na.rm = TRUE)) %>% 
  ggplot(aes(date, light_score)) +
  geom_col()
```

```{r}
light_mp %>% 
  filter(lubridate::year(date) > 2013) %>% 
  group_by(date) %>% 
  summarize(light_score = median(light_score, na.rm = TRUE)) %>% 
  ggplot(aes(date, light_score)) +
  geom_col()
```

```{r}
light_mp %>% 
  ggplot(aes(lubridate::month(date, label = TRUE))) +
  geom_bar()
```

The researchers only measured the light of McCormick Place during bird migration periods, which occur in the spring and autumn. 

```{r}
light_mp %>% 
  group_by(year = lubridate::year(date)) %>% 
  summarize(median_light = median(light_score, na.rm = TRUE)) %>% 
  ggplot(aes(year, median_light)) +
  geom_line() +
  scale_x_continuous(breaks = seq(2000, 2018, 1))
```

```{r}
light_mp %>% 
  group_by(month = lubridate::month(date, label = TRUE)) %>% 
  summarize(median_light = median(light_score, na.rm = TRUE)) %>% 
  ggplot(aes(month, median_light)) +
  geom_col() 
```

[^1] Winger Benjamin M., Weeks Brian C., Farnsworth Andrew, Jones Andrew W., Hennen Mary and Willard David E. Nocturnal flight-calling behaviour predicts vulnerability to artificial light in migratory birds. 286. Proceedings of the Royal Society B: Biological Sciences. http://doi.org/10.1098/rspb.2019.0364.
